### ISSUE TITLE
Cluster health?

### ISSUE THREAD

**Issue by JTrotta** [shubhamranjan/dotnet-etcd#10]
It would be nice to have this client command:

`etcdctl cluster-health`

**Comment by shubhamranjan** [comment]
Not sure if the grpc endpoints have exactly the same thing but maybe [this](https://github.com/etcd-io/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L180) might help. Maintenance calls as such will be added in a few weeks.

**Comment by shubhamranjan** [comment]
Feature to be included in v2.1.0
