### ISSUE TITLE
etcd-client support for k8s headless service

### ISSUE THREAD

**Issue by setood** [shubhamranjan/dotnet-etcd#106]
i want to use k8s headless service for connection to my etcd cluster with 3 nodes.
does dotnet-etcd support this feature? or i need pass to etcdClient one url for each etcd nodes?

**Comment by shubhamranjan** [comment]
Resolution for all endpoints via headless service is not supported at the moment. The only way right now is to pass url for each node.

**Comment by setood** [comment]
closed by mistake, still actual

**Comment by shubhamranjan** [comment]
This can be taken up now I guess since support for [client side load balancing](https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0) is out now.

**Comment by setood** [comment]
yeap, this will be work out of the box on .dotnet 5 or later. but it would break the retries from `CallEtcd` methods, because these methods retrying over `dotnet-etcd` `balancer` nodes.

**Comment by shubhamranjan** [comment]
hmm... I guess the whole balancing logic should be revamped to utilize the client's LB logic instead.

**Comment by setood** [comment]
this might be helpful https://docs.microsoft.com/en-us/aspnet/core/grpc/retries?view=aspnetcore-6.0#configure-a-grpc-retry-policy
