### ISSUE TITLE
Whether watch child node changes is supported

### ISSUE THREAD

**Issue by duyanming** [shubhamranjan/dotnet-etcd#11]

**Comment by shubhamranjan** [comment]
Need a bit of clarification here. By child node you mean child `keys` ? It would be great if you could provide an example to help me understand it better.

**Comment by shubhamranjan** [comment]
Apologies for the state change above. Closed by mistake.

**Comment by shubhamranjan** [comment]
Update: Watching over range of keys (directory) will be supported in the next release (within a few days) if that is what you are looking for.

**Comment by duyanming** [comment]
Thank you very much
