### ISSUE TITLE
Exception type when cancelling async operations

### ISSUE THREAD

**Issue by baseTwo** [shubhamranjan/dotnet-etcd#118]
**Some background on the problem I have with how cancellations are thrown in the grpc library**
Currently, the new Grpc.Net.Client throws a RpcException with a 'Canceled' StatusCode when async operations are canceled. This means that a Task's state IsFaulted and not IsCanceled. 

Also, handling exceptions when awaiting these tasks needs to be treated differently. Instead of catching all cancellations with the OperationCanceledException base type, they need to deal with a RpcException instead:

	var cancellationTokenSource = new CancellationTokenSource();
	cancellationTokenSource.CancelAfter(0);

	try { await etcdClient.StatusASync(new StatusRequest(), cancellationToken:cancellationTokenSource.Token); }
	catch (RpcException rpc) when (rpc.StatusCode == StatusCode.Cancelled) { /* handle cancellation */ }
	catch (Exception e) { /* handle errors */ };

**The solution I prefer**
Cancellations must throw OperationCanceledException. The fix for this is as follows:

When creating the GrpcChannel in the Balancer, update the GrpcChannelOptions to include this property:
ThrowOperationCanceledOnCancellation = true

**Alternatives I've considered**
Currently, I'm wrapping each call to the etcd library to catch the 'Canceled' RpcException, and rethrow it as OperationCanceledException.

**Comment by shubhamranjan** [comment]
Makes sense @baseTwo . Will look into it. Thanks !

**Comment by baseTwo** [comment]
I created (my first github) pull request. Perhaps it's wise to bump the versioning, since a different exception expected from each method could be considered a breaking change? Let me know your thoughts and if you have comments. Thanks :)
