### ISSUE TITLE
add separated community contrib project or repo

### ISSUE THREAD

**Issue by setood** [shubhamranjan/dotnet-etcd#157]
**Is your feature request related to a problem? Please describe.**
we want to contribute several methods that allow to get the maximum reliability from interaction with ETCD. 
For example, to keep lease alive by sending requests to several nodes.
However, these solutions may not be suitable for everyone and use external dependencies.

**Describe the solution you'd like**
it would be nice to make the source code more open for extension (get balancer nodes list for example)(we will make pull requests).
And create a separate `.csproj` and `.nuget` for code that not everyone needs.

**Describe alternatives you've considered**
alternatively, create a separate repository.
examples:
https://github.com/Polly-Contrib
https://github.com/serilog-contrib

**Comment by shubhamranjan** [comment]
IMO, stuff related to connection reliability should stay at the core of the repo. However,  if there are other additional features which are more around the the lib's core functionality, they can be moved to  new repo.  For e.g. an  etcd support for 
 `IConfiguration`  can be wrapped around in another package.
