### ISSUE TITLE
GrpcChannelOptions parameter configuration

### ISSUE THREAD

**Issue by SGStino** [shubhamranjan/dotnet-etcd#171]
**Is your feature request related to a problem? Please describe.**
I would like to set MaxReceiveMessageSize to a larger value, but since GrpcChannelOptions is created in the EtcdClient constructor, this is not possible.

**Describe the solution you'd like**
a `Action<GrpcChannelOptions> configureChannelOptions = null` parameter added to the constructor.
and `configureChannelOptions?.Invoke(options)`  at https://github.com/shubhamranjan/dotnet-etcd/blob/4db4737158132cef638d58a9fcd8001e10ecd878/dotnet-etcd/etcdClient.cs#L104
**Describe alternatives you've considered**
The whole `GrpcChannelOptions` object can't be passed into the constructor because the `MethodConfigs`, `throttlingPolicy`, `handler`, .. properties are set in the constructor already. And when passing in the entire object, you can't get those from the constructor.

And creating a custom configuration class with only the relevant properties, and copying them over sounds like wasted effort.

**Additional context**
Reason for changing the `GrpcChannelOptions` property:
```log
Grpc.Core.RpcException: Status(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.")
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at dotnet_etcd.EtcdClient.<>c__DisplayClass49_0.<<GetAsync>b__0>d.MoveNext()
```

**Comment by shubhamranjan** [comment]
Thanks for reporting this. This has been released in `6.2.0-beta`
