### ISSUE TITLE
Lock permission denied

### ISSUE THREAD

**Issue by careless6666** [shubhamranjan/dotnet-etcd#172]
**Describe the bug**
I have 2 instances of the same service with the following simply logic
Instance A:
create lease => leaseA
lock("someName", leaseA)

Instance B:
create lease => leaseB
lock("someName", leaseB)

Expected behavior:
Instance B wait, until unlock or lease expired

Real behavior:
Instance B sometimes receive error permission denied on client side, on server side: "auth: user name is empty"

We use tls auth and in wireshark i see that all request use tls without auth error. We use long live certificates

My experimental project
https://github.com/careless6666/etcd-cluster-issue/blob/main/Service/Controllers/DebugController.cs

etcd configuration:
#[member]
ETCD_NAME="stgetcd1z1.h.companyName"
ETCD_DATA_DIR="/var/lib/etcd/default"
ETCD_SNAPSHOT_COUNT=5000
ETCD_HEARTBEAT_INTERVAL=150
ETCD_ELECTION_TIMEOUT=3000
ETCD_QUOTA_BACKEND_BYTES=0
ETCD_LISTEN_CLIENT_URLS="https://0.0.0.0:2379/"
ETCD_ADVERTISE_CLIENT_URLS="https://stgetcd1z1.h.companyname:2379/"
ETCD_MAX_SNAPSHOTS=5
ETCD_MAX_WALS=5
ETCD_ENABLE_V2=false

#[proxy]
ETCD_PROXY="off"
ETCD_PROXY_FAILURE_WAIT=5000
ETCD_PROXY_REFRESH_INTERVAL=30000
ETCD_PROXY_DIAL_TIMEOUT=1000
ETCD_PROXY_WRITE_TIMEOUT=5000
ETCD_PROXY_READ_TIMEOUT=0

#[cluster]
ETCD_LISTEN_PEER_URLS="https://0.0.0.0:2380/"
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://stgetcd1z1.h.companyname:2380/"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER="stgetcd1z1.h.companyName=[https://stgetcd1z1.h.companyName:2380,stgetcd2z1.h.companyName=https://stgetcd2z1.h.companyName:2380,stgetcd3z1.h.companyName=https://stgetcd3z1.h.companyName:2380,stgetcd4z1.h.companyName=https://stgetcd4z1.h.companyName:2380,stgetcd5z1.h.companyName=https://stgetcd5z1.h.companyName:2380](https://stgetcd1z1.h.companyname:2380%2Cstgetcd2z1.h.companyname%3Dhttps//stgetcd2z1.h.companyName:2380,stgetcd3z1.h.companyName=https://stgetcd3z1.h.companyName:2380,stgetcd4z1.h.companyName=https://stgetcd4z1.h.companyName:2380,stgetcd5z1.h.companyName=https://stgetcd5z1.h.companyName:2380),"
ETCD_INITIAL_CLUSTER_TOKEN="eiphohCipoowe9OnaiPhiefu"
ETCD_DISCOVERY_FALLBACK="proxy"
ETCD_STRICT_RECONFIG_CHECK=true
ETCD_FORCE_NEW_CLUSTER=false

#[security]
ETCD_CERT_FILE="/etc/etcd/ssl/stgetcd1z1_server_cert.pem"
ETCD_KEY_FILE="/etc/etcd/ssl/stgetcd1z1_server_key.pem"
ETCD_CLIENT_CERT_AUTH=true
ETCD_TRUSTED_CA_FILE="/etc/etcd/ssl/ca.pem"
ETCD_PEER_CERT_FILE="/etc/etcd/ssl/stgetcd1z1_peer_cert.pem"
ETCD_PEER_KEY_FILE="/etc/etcd/ssl/stgetcd1z1_peer_key.pem"
ETCD_PEER_CLIENT_CERT_AUTH=true
ETCD_PEER_TRUSTED_CA_FILE="/etc/etcd/ssl/peer_ca.pem"
ETCD_PEER_CERT_ALLOWED_CN="stg-etcd-common"

#[logging]
ETCD_DEBUG=False
ETCD_LOG_LEVEL=info

#ExecStart=/bin/sh -c "GOMAXPROCS=$(nproc) /usr/local/bin/etcd $DAEMON_ARGS"

DAEMON_ARGS:
--listen-metrics-urls http://0.0.0.0:2385/ --auto-compaction-mode=periodic --auto-compaction-retention=1h

version 3.5.5

We can't reproduce with error on latest commit on main branch with grpc connection dns:///etcd-stg-3.companyName:2379, but version 6.0.1 not available new constructor with grpc options, can you publish new version?

**Comment by careless6666** [comment]
We have error in our tests, problems reproduced and in last version too

**Comment by shubhamranjan** [comment]
Will try to reproduce this and get back.

**Comment by careless6666** [comment]
I reproduce it with golang, I think problem inside etcd

**Comment by careless6666** [comment]
https://github.com/etcd-io/etcd/issues/14850

**Comment by shubhamranjan** [comment]
alright, then. Feel free to reopen this if this is something on this client
