### ISSUE TITLE
Possible NullReference

### ISSUE THREAD

**Issue by jvymazal** [shubhamranjan/dotnet-etcd#173]
Hello, thanks for implementing #171, however it looks like:
https://github.com/shubhamranjan/dotnet-etcd/blob/035b2dfbe953def485b2104cc9a9ca4060489fca/dotnet-etcd/etcdClient.cs#L99

is missing handling for case when user does not supply any options Action (default is null), then you get a null-reference on construction of etcdClient.

Regards,
Jiri

**Comment by shubhamranjan** [comment]
Will have a look. Thanks for reporting.

**Comment by shubhamranjan** [comment]
Thanks for reporting this. This has been released in `6.2.0-beta`

**Comment by jvymazal** [comment]
Thanks as well. Keep up the good work
