### ISSUE TITLE
Invalid port specified

### ISSUE THREAD

**Issue by pholodniak** [shubhamranjan/dotnet-etcd#182]
**Describe the bug**
Providing connection string with only host and port, adding second port to url.

**To Reproduce**
Initialize with connection string like "localhost:2379" will try to create url from following string "localhost:2379:2379".

**Expected behavior**
Create internal url with only http prefix (or https when ssl enabled).

Is there any reason of looking first for 3 colons? Swapping ifs order could resolve problem.
https://github.com/shubhamranjan/dotnet-etcd/blob/c82573f242e913af1017056385d7255267975a04/dotnet-etcd/etcdClient.cs#L115-L123

**Comment by shubhamranjan** [comment]
Please use prefix `http://` or `https://` . The dotnet grpc lib requires the host to be in this format,

So in your case, it would be `http://localhost:2379`
