### ISSUE TITLE
Cannot use constructor EtcdClient(string) anymore

### ISSUE THREAD

**Issue by GrzegorzFedoryka** [shubhamranjan/dotnet-etcd#184]
**Describe the bug**
Since there are 2 constructors with only etcdUri required, there is no possibility to use it as follows: `new EtcdClient(uri)`. You could create new one `public EtcdClient(string uri) : base(uri, default port, default ...)`
**To Reproduce**

**Expected behavior**
Be able to use constructor `var etcdClient = new EtcdClient(uri)`

**Screenshots**

**Additional context**

**Comment by shubhamranjan** [comment]
The obsolete constructor has been removed in #190 and there will be only 1 constructor going forward
