### ISSUE TITLE
cluster 

### ISSUE THREAD

**Issue by jinyuttt** [shubhamranjan/dotnet-etcd#19]
**Is your feature request related to a problem? Please describe.**
How does the cluster work? You demonstrated an etcd.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shubhamranjan** [comment]
Currently, it works by passing a single host. Current workaround is to have a tcp (grpc capable) loadbalancer on top of hosts which I know is unorthodox. 

I have planned to have it in the future release as soon as I am a bit free. Can't guarantee an ETA here though.

If you plan to develop and contribute the same, please go ahead and feel free to send a PR :)

**Comment by jinyuttt** [comment]
What is the way to judge that the connection is no longer available for the client that has been connected (the server is closed, the network is broken)

**Comment by shubhamranjan** [comment]
> What is the way to judge that the connection is no longer available for the client that has been connected (the server is closed, the network is broken)

Following up on this in #20

**Comment by shubhamranjan** [comment]
I plan to add support this post 15th June 19 if someone doesn't. Going through a bit of busy schedule.

**Comment by jinyuttt** [comment]
ok，我的能力有限，无法贡献

**Comment by shubhamranjan** [comment]
I have released this in an alpha package. Please do test it out and let me know if you face any issues.

**Comment by shubhamranjan** [comment]
Released with v3.0.0
