### ISSUE TITLE
connection close

### ISSUE THREAD

**Issue by jinyuttt** [shubhamranjan/dotnet-etcd#20]
What is the way to judge that the connection is no longer available for the client that has been connected (the server is closed, the network is broken)

**Comment by shubhamranjan** [comment]
The client is not publicly exposed yet for  but reconnect on failure / disconnect has been handled. If you want to have it expose, please do let me know with the use case.

**Comment by jinyuttt** [comment]
When a cluster is deployed, multiple nodes will not be released after I connect to one node. When the node server crashes, it is meaningless to use the node again.

**Comment by jinyuttt** [comment]
When a cluster is deployed, there are multiple nodes. Connecting to one of the nodes will not be released. When the server of the node crashes, it is meaningless to use the node again.

**Comment by shubhamranjan** [comment]
Got it. This use case would be handled automatically when #19 would be implemented.
