### ISSUE TITLE
new EtcdClient Expected，Please give more Example to new player

### ISSUE THREAD

**Issue by JulianDay** [shubhamranjan/dotnet-etcd#213]
**Describe the bug**
EtcdClient client = new EtcdClient("http://127.0.0.1:2379")

**Expected behavior**
Unable to determine the TLS configuration of the channel from address 'static://my-etcd-server/'. GrpcChannelOptions.Credentials must be specified when the address doesn't have a 'http' or 'https' scheme

**Comment by shubhamranjan** [comment]
Hi, can you share a [gist](https://gist.github.com/) of your example ?

**Comment by SethuramS** [comment]
Hi, I also faced the same issue while trying out the library.

Steps to reproduce:
1. Set up etcd cluster locally
2. Try connecting to etcd cluster using the steps mentioned in the readme
`var etcdClient = new EtcdClient("http://localhost:2379");`


Relevant stack trace:
```
Unhandled exception. System.InvalidOperationException: Unable to determine the TLS configuration of the channel from address 'static://my-etcd-server/'. GrpcChannelOptions.Credentials must be specified when the address doesn't have a 'http' or 'https' scheme. To call TLS endpoints, set credentials to 'ChannelCredentials.SecureSsl'. To call non-TLS endpoints, set credentials to 'ChannelCredentials.Insecure'.
   at Grpc.Net.Client.GrpcChannel.ResolveCredentials(GrpcChannelOptions channelOptions, Boolean& isSecure, List`1& callCredentials)
   at Grpc.Net.Client.GrpcChannel..ctor(Uri address, GrpcChannelOptions channelOptions)
   at Grpc.Net.Client.GrpcChannel.ForAddress(Uri address, GrpcChannelOptions channelOptions)
   at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
   at dotnet_etcd.EtcdClient..ctor(String connectionString, Int32 port, String serverName, Action`1 configureChannelOptions, Interceptor[] interceptors)
```

I was able to get it working by setting the `ChannelCredentials.Insecure` properly like below, but can this be set by default or mentioned in the readme?
```
var etcdClient = new EtcdClient("http://localhost:2379", configureChannelOptions: (options =>
{
    options.Credentials = ChannelCredentials.Insecure;
}));
```

**Comment by shubhamranjan** [comment]
Thanks @SethuramS for detailing out the issue. I will look into this

**Comment by turowicz** [comment]
Having the same issue but I don't use HTTP/HTTPS, I just pass "localhost".

```
var client = new EtcdClient("localhost", 2379, configureChannelOptions: options =>
{
    options.Credentials = ChannelCredentials.Insecure;
}) as IEtcdClient;
```
