### ISSUE TITLE
Should the host of EtcdClient be array?

### ISSUE THREAD

**Issue by spiderpoison** [shubhamranjan/dotnet-etcd#23]
I found in Golang, the host of EtcdClient is slice.
But dotnet-etcd the host of EtcdClient is string.
So I only can connect single-point of etcd. Is it right?

**Comment by shubhamranjan** [comment]
Yes, this is known and I have started working on a proper implementation with whatever time I get. I believe its the same as #19.

**Comment by shubhamranjan** [comment]
Closing as duplicate of #19
