### ISSUE TITLE
When using "Watch" or "WatchRange" function, how to catch "Grpc.Core.RpcException" unhandled exception when network disconnected?

### ISSUE THREAD

**Issue by tung-lin** [shubhamranjan/dotnet-etcd#34]
**Is your feature request related to a problem? Please describe.**
When using "Watch" or "WatchRange" function, we got "Grpc.Core.RpcException" unhandled exception when network disconnected.

**Describe the solution you'd like**
Some EtcdClient event or static event that can help us to catch expcetion in this situation.
Or do you know any Grpc.Core method or event that  can help us to handle exception?

**Screenshots**
Exception: 
![image](https://user-images.githubusercontent.com/19318874/68468513-2389dc80-0253-11ea-9cae-1c99826da2db.png)

Our code:
![image](https://user-images.githubusercontent.com/19318874/68468800-b460b800-0253-11ea-8f4f-9fc237f970d2.png)

**Additional context**
.net core 3.0 console app
dotnet-etcd v3.0.0
etcd docker image: quay.io/coreos/etcd:v3.3.15

**Comment by Kuo-Chun-Ting** [comment]
Some problem here

**Comment by shubhamranjan** [comment]
Try Something like this:
```
try
{
    // Your code here
} (RpcException ex) when (ex.StatusCode == StatusCode.Unavailable) 
{
    // Do something with the exception. 
}
```
@Kuo-Chun-Ting @tung-lin Let me know if it works for you.

**Comment by tung-lin** [comment]
Thanks for your applying message.

We add try catch, but it didn't work.
![image](https://user-images.githubusercontent.com/19318874/68489195-9611b100-0281-11ea-95ff-9717b682d014.png)

Our steps:
1. New EtcdClient
2. Call WatchRange method
3. Everying was perfect
4. We close the etcd service (or close the local network) after a few seconds
5. An Grpc.Core.RpcException unhandled exception occurred!

I guess the reason is as follows:
In the method of WatchRange (line 649 in watchClient.cs), you add try catch outside the Task.Run.
So "await watcher.ResponseStream.MoveNext()" will throw exception when network disconnected.
![image](https://user-images.githubusercontent.com/19318874/68490310-b6426f80-0283-11ea-9766-338a068e5d95.png)

Maybe you can add try catch "inside" the Task.Run, and notify user when error occurred by calling custom error handler Action or triggering error event.

**Comment by shubhamranjan** [comment]
Oh I see. You want an exception  after the watch has been initiated and network disconnects thereafter. I will  push these changes. Or if you want to make a PR, you are most welcome.

**Comment by shubhamranjan** [comment]
> Some EtcdClient event or static event that can help us to catch exception in this situation.

@tung-lin  Do you mean that you are able to get an exception but rather want the exception handled through some event handler that can be passes as a parameter ?

**Comment by tung-lin** [comment]
@shubhamranjan  Passing event handler (Action) as a parameter sounds good and better than event delegate.
![image](https://user-images.githubusercontent.com/19318874/68529583-2e1fa100-033b-11ea-8f3e-3e906e31f5b9.png)
In this way, we can clearer know where the error comes from and call the Watch/WatchRange method again.

**Comment by shubhamranjan** [comment]
@tung-lin I have pushed the changes ( https://github.com/shubhamranjan/dotnet-etcd/pull/35 ) but it would take me a while to release a new build as I plan to release it with fixes to other issues. In the meantime, you can test the changes and if possible, do give a feedback whether it helps you or not.

**Comment by tung-lin** [comment]
Thanks for your help.

BTW, how should we watch prefix key using "WatchRange" method?
Our key is "schedule/", and we want to watch all keys under "schedule/" (schedule/1, schedule/2, schedule/xxx)
We don't know how to set the RangeEnd parameter.
If we set ByteString.CopyFromUtf8("\0"), it watch almost all keys...

**Comment by shubhamranjan** [comment]
Try out the overloads available which take the prefix path and do it for you.

E.g. ` public void WatchRange(string path, Action<WatchResponse> method, Metadata headers = null)`

There are many more similar overloads available.

**Comment by alvincfan** [comment]
@tung-lin and future viewers

To set range end based on prefix path, try 

RangeEnd = ByteString.CopyFromUtf8(EtcdClient.GetRangeEnd(prefix))
