### ISSUE TITLE
Using this client with IConfiguration 

### ISSUE THREAD

**Issue by Nitin5acc** [shubhamranjan/dotnet-etcd#36]
Hello,

Is there a way to use this client with IConfiguration?

**Comment by shubhamranjan** [comment]
Hi @Nitin5acc ,
Not sure what you want to achieve here. Are you talking about using the lib via DI ? If that's the case, I can provide a public interface for that.

**Comment by Nitin5acc** [comment]
We are planning to use etcd to store configuration value (i.e. Database connection string ). Currently, we are using an IConfiguration builder to read other config values. We would like to use your Etcd client with IConfiguration.

**Comment by shubhamranjan** [comment]
> https://github.com/rajanadar/VaultSharp

Can't see what exactly are you looking for. Can you show an example snippet depicting how you exactly want to use it.

**Comment by Nitin5acc** [comment]
You can ignore this. We did achieve what was needed. We were trying to create configuration client.
Onr more thing - 
Is there a way to get the key-value pairs in a hierarchical way like the suffix?

**Comment by shubhamranjan** [comment]
> Is there a way to get the key-value pairs in a hierarchical way (like the suffix), Not just Values but key-value pairs?

Are you looking for all keys under a certain path ? Something like:

```
await client.GetRangeAsync(<PREFIX_STRING>);
// E.g. Get all keys with pattern "foo/*" in async
await client.GetRangeAsync("foo/");
```

**Comment by Nitin5acc** [comment]
Yes.

**Comment by shubhamranjan** [comment]
Well, that's already there.
Ref: https://github.com/shubhamranjan/dotnet-etcd#get-multiple-keys-with-a-common-prefix

**Comment by Nitin5acc** [comment]
Hello,
Two more Questions 
1. Can we have nested key-value pair where the value would be an object for the given key? 
1. Can we have a folder structure or hierarchical within the cluster? and retrieve all values under given path?
