### ISSUE TITLE
Store data in hierarchically organized directories

### ISSUE THREAD

**Issue by Nitin5acc** [shubhamranjan/dotnet-etcd#37]
Hello,

Can we Store data in hierarchically organized directories, as in a standard filesystem?
Something like -
/config
/database
/feature-flags
/verbose-logging
/redesign

**Comment by shubhamranjan** [comment]
Starting v3+, etcd is a flat key space, no hierarchy.

You can create keys like `/config/key1` , `/config/category1/key2` to achieve this. So your directory path would be a part  of your key itself.
