### ISSUE TITLE
user name is empty error is shown if authentication is enabled 

### ISSUE THREAD

**Issue by Nitin5acc** [shubhamranjan/dotnet-etcd#38]
**Describe the bug**
When Authentication is enabled. I am not able to get the values. 

> user name is empty

 is returned. 

**To Reproduce**
`_etcdClient = new dotnet_etcd.EtcdClient(_client.Settings.ConnectionString, _client.Settings.Port, _client.Settings.UserName,_client.Settings.Password);`

a
**Expected behavior**
I should get the value ( ETCD cli does return the value)

**Comment by beckjin** [comment]
You can try it like this :
```
var client = new EtcdClient("http://127.0.0.1:2379");

var authRes = client.Authenticate(new Etcdserverpb.AuthenticateRequest { Name = "admin", Password = "123456" });

var header = new Metadata
{
	{ "Authorization", authRes.Token }
};

var key = "/foo/bar";

client.Put("/foo/bar", "1", header);
```

**Comment by shubhamranjan** [comment]
> You can try it like this :
> 
> ```
> var client = new EtcdClient("http://127.0.0.1:2379");
> 
> var authRes = client.Authenticate(new Etcdserverpb.AuthenticateRequest { Name = "admin", Password = "123456" });
> 
> var header = new Metadata
> {
>   { "Authorization", authRes.Token }
> };
> 
> var key = "/foo/bar";
> 
> client.Put("/foo/bar", "1", header);
> ```

Yes. Documentation is something which is pending from long. I need to update them asap.
