### ISSUE TITLE
Implement the gRPC Naming like go-clientv3 

### ISSUE THREAD

**Issue by ElderJames** [shubhamranjan/dotnet-etcd#39]
Can implement the Naming like go client?

https://github.com/etcd-io/etcd/tree/master/clientv3/naming

**Comment by shubhamranjan** [comment]
Can you elaborate with an example showing the behavior of how would you like to use the client ?.

**Comment by shubhamranjan** [comment]
@ElderJames This is exactly what you want right ? : https://etcd.io/docs/v3.3.12/dev-guide/grpc_naming/

**Comment by ElderJames** [comment]
Exactly. :)
