### ISSUE TITLE
Exception handling issue in Watch API

### ISSUE THREAD

**Issue by xontab** [shubhamranjan/dotnet-etcd#42]
**Describe the bug**
In the 3.1.0 release, a new exception handler parameter was added to the watch API, however this only works properly when `StatusCode` is not `Unavailable`
https://github.com/shubhamranjan/dotnet-etcd/blob/cd0afcbe629c0a00e52355bb22e5a13755450f41/dotnet-etcd/watchClient.cs#L71-L78

This is because the original exception is still thrown when  `StatusCode` is `Unavailable` and thus this is causing side effects since the etcd watch logic is inside a `Task`.
https://github.com/shubhamranjan/dotnet-etcd/blob/cd0afcbe629c0a00e52355bb22e5a13755450f41/dotnet-etcd/watchClient.cs#L93

**To Reproduce**
1. Create a connection when etcd is down
2. Use the Watch API (any overload) with exception handling
3. Exception is thrown from `Task`

**Expected behavior**
Exception details should be handled in the `exceptionHandler` action

**Comment by xontab** [comment]
@shubhamranjan Does it make sense that we wrap the following code inside the `catch` block also? 
https://github.com/shubhamranjan/dotnet-etcd/blob/cd0afcbe629c0a00e52355bb22e5a13755450f41/dotnet-etcd/watchClient.cs#L71-L78

**Comment by shubhamranjan** [comment]
Noted. I will simplify it to always call exception handler.
