### ISSUE TITLE
Cluster distribution

### ISSUE THREAD

**Issue by yoricksmeets** [shubhamranjan/dotnet-etcd#45]
I have a application where I would create an etcd client when needed and not keep a single etcd client around for all requests.

If I read through the code it looks like the round-robin technique of handing out the etcd node connections always starts with the first node of the provided node list. This results in an uneaven load distribution where the first node would get far more requests if the clients are short-lived.

Maybe it is better to initialize the _lastNodeIndex of the EtcdClient with a random selected node from the node list? Or change the GetNextNodeIndex method so it chooses a random node when the _lastNodeIndex is -1. 
Setting it on the _lastNodeIndex directly on construction would be easier but the number stored in _lastNodeIndex would not actualy be the last node used.

**Comment by shubhamranjan** [comment]
> initialize the _lastNodeIndex of the EtcdClient with a random selected node from the node list.

This sounds like a better idea.

**Comment by yoricksmeets** [comment]
The changes made will now always use random to pick a new node but I was expecting that we would only use random for the initial start node and use the increase by one method after selecting the first node.

Given a 3 node cluster.
For this cluster we start 5 clients. The clients will create a number of streams over their lifetime:

1. Will start 21 streams
2. Will start 10 streams
3. Will start 19 streams
4. Will start 1 stream
5. Will start 3 streams

The solution before this change would have the following behaviour:
- 1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3
- 1,2,3,1,2,3,1,2,3,1
- 1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3
- 1
- 1,2,3
with the disadvantage that it would always start on node 1 given this more load but after the initial selection of node 1 it would spread the load even over the rest of the nodes

The solution as it is implemented now only checks if the selected node differs from the node it was currently using, given the following hypothetical behaviour since random is used:
- 2,1,2,3,1,2,1,2,1,2,1,2,3,2,1,3,1,2,3,2,3,1
- 1,2,1,3,2,3,1,2,1,3
- 2,3,1,3,2,3,2,1,3,1,3,1,2,1,3,2,3,1
- 3
- 1,3,1
Not giving a disadvantage to node 1, but not guarenting a even spread of the load since the random function in combination with the rule that the node must change could render series like: 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 not selecting node 2 for a long time. We can expect each node to be selected about the same number of times over a long period but in short selections of the series this not guaranteed.

The solution that I wanted to describe is only selecting the first node using the random function and using +1 after the initial selection would give the following series:
- 1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3
- 3,1,2,3,1,2,3,1,2,3
- 2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1
- 2
- 3,1,2
This prevents node 1 from being over represented in the selection but will guarantee an even spread over the nodes after selecting the first node.
