### ISSUE TITLE
Use methods with generics to implement retry

### ISSUE THREAD

**Issue by yoricksmeets** [shubhamranjan/dotnet-etcd#46]
Is there any reason why there is so much retry logic copied throughout the codebase Using a method with generics and a Func this could be refactored to a more maintainable codebase. 

For example this method:
```csharp
public AuthenticateResponse Authenticate(AuthenticateRequest request, Grpc.Core.Metadata headers = null,
    DateTime? deadline = null,
    CancellationToken cancellationToken = default(CancellationToken))
{
    AuthenticateResponse response = new AuthenticateResponse();
    bool success = false;
    int retryCount = 0;
    while (!success)
    {
        try
        {
            response = _balancer.GetConnection().authClient
                .Authenticate(request, headers, deadline, cancellationToken);
            success = true;
        }
        catch (RpcException ex) when (ex.StatusCode == StatusCode.Unavailable)
        {
            retryCount++;
            if (retryCount >= _balancer._numNodes)
            {
                throw ex;
            }
        }
    }

    return response;
}
```

Can become:
```csharp
public AuthenticateResponse Authenticate(AuthenticateRequest request, Grpc.Core.Metadata headers = null,
    DateTime? deadline = null,
    CancellationToken cancellationToken = default(CancellationToken))
{
    return CallEtcd((con) => con.authClient.Authenticate(request, headers, deadline, cancellationToken));
}
```

With the use of a simple helper function:
```csharp
private TResponse CallEtcd<TResponse>(Func<Connection, TResponse> etcdCallFunc)
{
    TResponse response = default(TResponse);
    bool success = false;
    int retryCount = 0;
    while (!success)
    {
        try
        {
            response = etcdCallFunc.Invoke(_balancer.GetConnection());
            success = true;
        }
        catch (RpcException ex) when (ex.StatusCode == StatusCode.Unavailable)
        {
            retryCount++;
            if (retryCount >= _balancer._numNodes)
            {
                throw;
            }
        }
    }

    return response;
}
```

I have also changed 'throw ex' to simple 'throw' because 'throw ex' removes the original stack trace and creates a new one on the place of the throw while a simple 'throw' keeps the original stack trace that should provide more details. Especially with the helper function: without this change all stack traces would point to the helper function as the source of the exception.

**Comment by shubhamranjan** [comment]
I totally agree on all the points mentioned. There's a lot of scope for refactoring. Thanks for pointing these out.

**Comment by shubhamranjan** [comment]
>I have also changed 'throw ex' to simple 'throw' because 'throw ex' removes the original stack trace and creates a new one on the place of the throw while a simple 'throw' keeps the original stack trace that should provide more details. Especially with the helper function: without this change all stack traces would point to the helper function as the source of the exception.

@yoricksmeets Are you implementing these changes or should I proceed with their implementation ?

**Comment by yoricksmeets** [comment]
@shubhamranjan I'm not implementing them at this moment. I can make some time later this week to implement these changes.

**Comment by yoricksmeets** [comment]
I'm starting to work on this issue

**Comment by yoricksmeets** [comment]
I arrived at the methods that use a AsyncDuplexStreamingCall and I was reading back through the issues why there is a errorHandler action in the function signature. 
I think the problem raised in #34 is the reason this errorHandler action is included, but I think that if the watch operations return a Task instead of void, as pointed out in #40, it will give the user the option to catch the exception by handling the task that is returned by the  method.

This setup will not return the exception that is thrown within the task so the caller has no way to handle the exception:
```{csharp}
        [Test]
        public void TestVoidVsTask()
        {
            try
            {
                Watcher();
            }
            catch (Exception e)
            {
                // Never reached because Watcher() will never throw
            }
        }

        public async void Watcher()
        {
            while (true)
            {
                try
                {
                    Task watcherTask = Task.Run(async () =>
                    {
                        // stuff
                        throw new Exception();
                    });
                    await watcherTask;
                    return;
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
        }
```

The exception will now crash the entire program. And wrapping the call to 'Watcher()' in the test method with a try-catch will not help because the exception is not propagated.

This following code will propagate the error and gives the caller the option to handle the exceptions.

```{csharp}
        [Test]
        public void TestVoidVsTask()
        {
            try
            {
                Watcher().GetAwaiter().GetResult();
            }
            catch (Exception e)
            {
                // Handle exception
            }
        }

        public async Task Watcher()
        {
            while (true)
            {
                try
                {
                    Task watcherTask = Task.Run(async () =>
                    {
                        // stuff
                        throw new Exception();
                    });
                    await watcherTask;
                    return;
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
        }
```

I was hoping to remove the exceptionHandler and change the return type from 'async void' to 'async Task' but this will break the API, so I would like your view on this matter @shubhamranjan

**Comment by shubhamranjan** [comment]
Yeah, the exception handler can be removed with return type changed to `Task`.  We can do this change, a breaking change but not a feature removal. Will be fine.
