### ISSUE TITLE
Add name option when adding new member.

### ISSUE THREAD

**Issue by alenjursic1997** [shubhamranjan/dotnet-etcd#52]
**MemberAddRequest() method**
I't would be really nice to be able to set name parameter when registering/adding new nodes (clusters).
I'm implementing discovery service for consul and etcd, but it is impossible to do it for etcd now, because I need to find it by it's name. Go library for etcd already has this option.

**Comment by shubhamranjan** [comment]
I will check how they have implemented and get back on this one. Cannot see an grpc parameter provided in their contract.

**Comment by shubhamranjan** [comment]
The grpc api currently doesn't have a parameter exposed. Hence, cannot add this feature atm. Will raise an issue and see what response do I get from them.


Ref: https://etcd.io/docs/v3.3.12/dev-guide/api_reference_v3/#service-cluster-etcdserveretcdserverpbrpcproto

**Comment by alenjursic1997** [comment]
Hi,
This is the way to register member in ETCD as described here: https://etcd.io/docs/v3.4.0/dev-internal/discovery_protocol/

Example:
curl -X PUT http://example.com/v2/keys/_etcd/registry/${UUID}/${member_id}?prevExist=false -d value="${member_name}=${member_peer_url_1}&${member_name}=${member_peer_url_2}"

As you see, there is a possibility to add "member_name".
Is it posible to do this with your library like that:

var addReq = new MemberAddRequest();
addReq.PeerURLs.Add("testName=http://localhost:1234"); //just example
MemberAddResponse res = await _client.MemberAddAsync(addReq);

**Comment by shubhamranjan** [comment]
Thats the v2 api which supports the rest protocol only. gRPC is supported with v3+ (which this library is built on top of) and the grpc contract of etcd server doesn't have this parameter.

Thanks for the reference though, I will use it to raise an issue there.

**Comment by shubhamranjan** [comment]
> addReq.PeerURLs.Add("testName=http://localhost:1234"); //just example

This format doesn't seem to be supported as of now.

**Comment by shubhamranjan** [comment]
Raised an issue: https://github.com/etcd-io/etcd/issues/12031

**Comment by shubhamranjan** [comment]
@alenjursic1997 Maybe you can explain your use case on the raised issue to help them understand better.
