### ISSUE TITLE
Is there a way to return all keys

### ISSUE THREAD

**Issue by satishviswanathan** [shubhamranjan/dotnet-etcd#53]
How can I get all the keys. Similar to the way we run the following command which returns all the keys.

etcdctl.exe --user root:password get --from-key '

**Comment by shubhamranjan** [comment]
```
// For fetching all keys
   await client.GetRangeAsync("/");

// For fetching all keys under foo
  await client.GetRangeAsync("foo/");
```

Hope this helps

**Comment by satishviswanathan** [comment]
@shubhamranjan Not sure if I'm missing something. I'm usinfg etcd version etcd-v3.4.3 and i'm trying to return all the keys using but doesn't return anything.

// For fetching all keys
   await client.GetRangeAsync("/");

**Comment by shubhamranjan** [comment]
Will check this over the weekend. Re-opening to ensure I don't miss this out.

**Comment by shubhamranjan** [comment]
Identified root cause. Will release a fix soon.

**Comment by shubhamranjan** [comment]
Meanwhile you can test via `etcdClient.GetRange("");` or `await etcdClient.GetRangeAsync("");`
