### ISSUE TITLE
etcdclient

### ISSUE THREAD

**Issue by jinyuttt** [shubhamranjan/dotnet-etcd#57]
**Describe the bug**
 EtcdClient client = new EtcdClient("127.0.0.1",2379);

error:

System.UriFormatException : "invalid URI: invalid URI scheme.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by shubhamranjan** [comment]
Protocol specification is required. Try this:  `new EtcdClient("http://127.0.0.1:2379");`
