### ISSUE TITLE
MemberAdd - accept url only, no name

### ISSUE THREAD

**Issue by JTrotta** [shubhamranjan/dotnet-etcd#9]
Usually when adding a member we also set a name:
etcdctl member add NAME http://a.b.c.d:2380

Is it optional or useless?

**Comment by shubhamranjan** [comment]
The CLI does require that, however, the current implementation of etcd's grpc [protofile](https://github.com/etcd-io/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto) does not expose any such property in the request.

**Comment by hexfusion** [comment]
@JTrotta @shubhamranjan is right the name should be populated at startup. etcdctl has this input to member add but if you read the code it is only used to populate startup flags/ENV for new member and is not passed via MemberAdd.
