### ISSUE TITLE
GetRange includes line return to response

### ISSUE THREAD

**Issue by CriggerMarg** [shubhamranjan/dotnet-etcd#92]
**Describe the bug**
RangeResponse GetRange(
      string prefixKey,
      Metadata headers = null,
      DateTime? deadline = null,
      CancellationToken cancellationToken = default (CancellationToken))
includes line return to key values.

**To Reproduce**
1. Load some keys to etcd
2. Fetch them with GetRange method
3. Look to each key Value.Span property
4. You'll see \r at the end of value.

**Expected behavior**
Do not include line return as GetVal method does.

**Additional context**
We are using prefixes like /API_NAME/Key_Name "key_Value"

**Comment by shubhamranjan** [comment]
Thanks for reporting. I double check and see that the `GetVal` method returns trimmed response from code. However, ` \r ` is not something that is being added by the library. Its most likely the actual value inside etcd contains ` \r `, hence you are getting it in response.

**Comment by CriggerMarg** [comment]
Most likely. Thanks for checking.
